# Generated by Django 6.0.2 on 2026-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_configuracionsitio_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nombre_empresa',
            field=models.CharField(default='TU MARCA', help_text='Nombre que se mostrará en el encabezado con tipografía urbana.', max_length=100),
        ),
    ]
