# Generated by Django 6.0.2 on 2026-02-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_configuracionsitio_nombre_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='email',
            field=models.EmailField(blank=True, help_text='Ej: ventas@tumarca.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='texto_informacion',
            field=models.TextField(blank=True, help_text='Detalles de talles, envíos, etc. (Podés usar Enter para separar párrafos)', null=True),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Ej: +5491123456789', max_length=20, null=True),
        ),
    ]
