# Generated by Django 6.0.2 on 2026-02-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_pedido_detallepedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: S, M, L o 42, 44', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='talle_elegido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='nombre_empresa',
            field=models.CharField(default='TU MARCA', help_text='Nombre que se mostrará en el encabezado.', max_length=100),
        ),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='texto_informacion',
            field=models.TextField(blank=True, help_text='Info de envíos, talles, etc.', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='talles',
            field=models.ManyToManyField(blank=True, help_text='Seleccioná los talles disponibles', to='catalogo.talle'),
        ),
    ]
