# Generated by Django 6.0.2 on 2026-02-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_talle_detallepedido_talle_elegido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='pedido',
            name='apellido',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.TextField(default='', max_length=20),
        ),
    ]
